# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-10 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='percentage',
            field=models.IntegerField(default=5),
        ),
    ]
