# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-10 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_coupon_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='multiple_tickets',
            field=models.BooleanField(default=False),
        ),
    ]
