# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-14 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_multiple_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_paid',
            field=models.DateTimeField(null=True),
        ),
    ]
