# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-17 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprice',
            name='early_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticketprice',
            name='early_price_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketprice',
            name='regular_count',
            field=models.IntegerField(default=0),
        ),
    ]
