# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-20 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_auto_20170717_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('diet', models.CharField(choices=[('Omnivorous', 'Omnivorous'), ('Vegetarian', 'Vegetarian'), ('Others', 'Others')], default='Omnivorous', max_length=30)),
                ('tagline', models.CharField(max_length=100)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
