# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-12 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_created_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='number_of_usage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='coupon_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='tickets.Coupon'),
        ),
    ]
