# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20170812_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
