# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symposion_sponsorship', '0002_auto_20160517_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sponsors')),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_link', to='symposion_sponsorship.Sponsor')),
            ],
        ),
    ]
